### ISSUE TITLE
Disable Pay Later and Split Payment Options

### ISSUE THREAD

**Issue by Maddumage** [Nets-mobile-acceptance/Easy-Android-SDK#2]
Hi,
I am currently implementing Easy Mobile SDK for a react native application. My Client wants to disable the Pay Later and Split Payment options from the payment window. Is it possible to do?. I read all the documentation but I couldn't find anything about that.
Thanks

**Comment by Tim-Badin** [comment]
Hi @Maddumage 
Yes, this is possible. Which payments methods are available in the Easy checkout depends on your client's Easy agreement.
They can select among Cards, PayPal, Swish, MobilePay, Vipps, Pay Later or Split. Kindly refer them to their account manager in Nets to confirm their wishes.
Best regards,
Tim - Nets
